### ISSUE TITLE
Error when starting up app

### ISSUE THREAD

**Issue by nicknetender** [spree-contrib/spree_globalize#105]
On a fresh Spree installation I get the following error

```
/usr/local/rvm/gems/ruby-3.2.0/bundler/gems/spree_globalize-1c6eb9e15daa/lib/spree_globalize/engine.rb:11:in `block in <class:Engine>': uninitialized constant SpreeGlobalize::Configuration (NameError)

      SpreeGlobalize::Config = SpreeGlobalize::Configuration.new
                                             ^^^^^^^^^^^^^^^
	from /usr/local/rvm/gems/ruby-3.2.0/gems/railties-7.0.6/lib/rails/initializable.rb:32:in `instance_exec'
	from /usr/local/rvm/gems/ruby-3.2.0/gems/railties-7.0.6/lib/rails/initializable.rb:32:in `run'
	from /usr/local/rvm/gems/ruby-3.2.0/gems/railties-7.0.6/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /usr/local/rvm/rubies/ruby-3.2.0/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
	from /usr/local/rvm/rubies/ruby-3.2.0/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/rvm/rubies/ruby-3.2.0/lib/ruby/3.2.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /usr/local/rvm/rubies/ruby-3.2.0/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/local/rvm/rubies/ruby-3.2.0/lib/ruby/3.2.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /usr/local/rvm/gems/ruby-3.2.0/gems/railties-7.0.6/lib/rails/initializable.rb:50:in `each'
	from /usr/local/rvm/gems/ruby-3.2.0/gems/railties-7.0.6/lib/rails/initializable.rb:50:in `tsort_each_child'
	from /usr/local/rvm/rubies/ruby-3.2.0/lib/ruby/3.2.0/tsort.rb:415:in `call'
	from /usr/local/rvm/rubies/ruby-3.2.0/lib/ruby/3.2.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /usr/local/rvm/rubies/ruby-3.2.0/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/local/rvm/rubies/ruby-3.2.0/lib/ruby/3.2.0/tsort.rb:347:in `each'
	from /usr/local/rvm/rubies/ruby-3.2.0/lib/ruby/3.2.0/tsort.rb:347:in `call'
	from /usr/local/rvm/rubies/ruby-3.2.0/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/local/rvm/rubies/ruby-3.2.0/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
	from /usr/local/rvm/rubies/ruby-3.2.0/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
	from /usr/local/rvm/gems/ruby-3.2.0/gems/railties-7.0.6/lib/rails/initializable.rb:60:in `run_initializers'
	from /usr/local/rvm/gems/ruby-3.2.0/gems/railties-7.0.6/lib/rails/application.rb:372:in `initialize!'
	from /app/app/src/config/environment.rb:5:in `<main>'
	from /usr/local/rvm/gems/ruby-3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /usr/local/rvm/gems/ruby-3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /usr/local/rvm/gems/ruby-3.2.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /usr/local/rvm/gems/ruby-3.2.0/gems/zeitwerk-2.6.10/lib/zeitwerk/kernel.rb:38:in `require'
	from /usr/local/rvm/gems/ruby-3.2.0/gems/railties-7.0.6/lib/rails/application.rb:348:in `require_environment!'
	from /usr/local/rvm/gems/ruby-3.2.0/gems/railties-7.0.6/lib/rails/command/actions.rb:28:in `require_environment!'
	from /usr/local/rvm/gems/ruby-3.2.0/gems/railties-7.0.6/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
	from /usr/local/rvm/gems/ruby-3.2.0/gems/railties-7.0.6/lib/rails/commands/generate/generate_command.rb:21:in `perform'
	from /usr/local/rvm/gems/ruby-3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
	from /usr/local/rvm/gems/ruby-3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/rvm/gems/ruby-3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
	from /usr/local/rvm/gems/ruby-3.2.0/gems/railties-7.0.6/lib/rails/command/base.rb:87:in `perform'
	from /usr/local/rvm/gems/ruby-3.2.0/gems/railties-7.0.6/lib/rails/command.rb:48:in `invoke'
	from /usr/local/rvm/gems/ruby-3.2.0/gems/railties-7.0.6/lib/rails/commands.rb:18:in `<main>'
	from /usr/local/rvm/gems/ruby-3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /usr/local/rvm/gems/ruby-3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from bin/rails:4:in `<main>'
```

Gemfile
```
gem 'spree', '~> 4.6'
gem 'spree_sample', '~> 4.6'
gem 'spree_emails', '~> 4.6'
gem 'spree_backend', '~> 4.6'
gem 'spree_gateway', '~> 3.10'
gem 'spree_auth_devise', '~> 4.5'
gem 'spree_i18n', '~> 5.1'
gem 'spree_dev_tools', require: false, group: %w[test development]

gem 'spree_globalize', github: 'spree-contrib/spree_globalize'
```

**Comment by MahmoudAliIbrahim** [comment]
Did you get it fixed?
